---
kafka_enabled: true # Enable Kafka integration

# Logger configuration
logger:
  max_size: 10 # Maximum size of the log file in MB
  max_backups: 5 # Maximum number of backup log files to keep
  max_age: 30 # Maximum age of a log file in days
  compression: true # Whether to compress old log files
  local_time: true # Use local time for timestamps in logs

# Database configuration
database:
  # Database type can be 'mysql', 'postgres', 'mongodb'
  type: "mysql"
  host: "0.0.0.0"
  port: 3306
  user: "root"
  password: "password"
  name: "shop"
  ssl: false
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: "30s"
  conn_max_idle_time: "30s"

  # Options for MongoDB
  auth_source: "admin" # Authentication source for MongoDB
  replica_set: "rs0" # Replica set name for MongoDB
  connection_timeout: 5000 # Connection timeout in milliseconds
  server_selection_timeout: 5000 # Server selection timeout in milliseconds
