services:
  vrecommendation_ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT:-9999}:${CONTAINER_PORT:-9999}"
    environment:
      - HOST_PORT=${HOST_PORT:-9999}
      - CONTAINER_PORT=${CONTAINER_PORT:-9999}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - vrecommendation_ai_network
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./tasks:/app/tasks
      - ./logs:/app/logs
      - ./models:/app/models

  prometheus_vrecommendation_ai:
    image: prom/prometheus:latest
    restart: "always"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "${PROMETHEUS_HOST_PORT:-9090}:${PROMETHEUS_CONTAINER_PORT:-9090}"
    env_file:
      - .env
    networks:
      - vrecommendation_ai_network

networks:
  vrecommendation_ai_network:
    driver: bridge

volumes:
  poetry_cache: