[project]
name = "ai_server"
version = "0.1.0"
description = "This is AI Server."
authors = [
    {name = "VennV", email = "hyplex9009@gmail.com"}
]
license = {text = "Apache License 2.0"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi==0.115.6",
    "graphviz==0.20.3",
    "pandas==2.2.3",
    "prometheus-client==0.21.0",
    "prometheus-fastapi-instrumentator==7.0.0",
    "pydantic==2.10.4",
    "PyYAML==6.0.2",
    "rapidfuzz==3.11.0",
    "ruamel.base==1.0.0",
    "ruamel.yaml==0.17.32",
    "mysql-connector-python==8.0.33",
    "redis==4.6.0",
    "scikit-learn==1.6.0",
    "scikit-surprise==1.1.4",
    "surprise==0.1",
    "uvicorn==0.34.0",
    "numpy<2.0.0",
    "poetry==2.1.3",
    "sqlalchemy==2.0.41",
    "loguru==0.7.3"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "black",
    "flake8",
    "mypy",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py310']

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
