#!/bin/bash

# VRecommendation - LAN Access Setup Script for Linux/macOS

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo ""
echo "===================================================================="
echo "   VRecommendation - LAN Access Configuration Setup"
echo "===================================================================="
echo ""

# Get the script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo -e "${BLUE}[INFO]${NC} Detecting network configuration..."
echo ""

# Detect OS and get IP addresses
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    IPS=($(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}'))
else
    # Linux
    IPS=($(ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v 127.0.0.1))
    if [ ${#IPS[@]} -eq 0 ]; then
        # Fallback for older systems
        IPS=($(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | cut -d: -f2))
    fi
fi

if [ ${#IPS[@]} -eq 0 ]; then
    echo -e "${RED}[ERROR]${NC} No IPv4 address found. Please check your network connection."
    exit 1
fi

echo "Found ${#IPS[@]} IPv4 address(es):"
echo ""

# Display all IPs
for i in "${!IPS[@]}"; do
    echo "  [$((i+1))] ${IPS[$i]}"
done
echo ""

# Auto-select if only one IP, otherwise ask user
if [ ${#IPS[@]} -eq 1 ]; then
    SELECTED_IP="${IPS[0]}"
    echo -e "${BLUE}[INFO]${NC} Auto-selected: $SELECTED_IP"
else
    read -p "Select IP address number [1-${#IPS[@]}] or enter custom IP: " IP_CHOICE

    # Check if it's a number within range
    if [[ "$IP_CHOICE" =~ ^[0-9]+$ ]] && [ "$IP_CHOICE" -ge 1 ] && [ "$IP_CHOICE" -le ${#IPS[@]} ]; then
        SELECTED_IP="${IPS[$((IP_CHOICE-1))]}"
    else
        # Assume user entered custom IP
        SELECTED_IP="$IP_CHOICE"
    fi
fi

echo ""
echo -e "${BLUE}[INFO]${NC} Using IP address: $SELECTED_IP"
echo ""

# Validate IP format
if ! [[ $SELECTED_IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo -e "${RED}[ERROR]${NC} Invalid IP address format: $SELECTED_IP"
    exit 1
fi

# Confirm with user
read -p "Continue with this IP? (y/n): " CONFIRM
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
    echo -e "${YELLOW}[CANCELLED]${NC} Setup cancelled by user."
    exit 0
fi

echo ""
echo -e "${BLUE}[INFO]${NC} Creating .env file..."

# Backup existing .env if present
if [ -f ".env" ]; then
    echo -e "${BLUE}[INFO]${NC} Backing up existing .env to .env.backup"
    cp ".env" ".env.backup"
fi

# Create .env file
cat > ".env" << EOF
# ============================================
# VRecommendation - Environment Configuration
# ============================================
# Generated by setup-lan-access.sh
# Date: $(date)
# ============================================

# ==========================================
# HOST IP Configuration
# ==========================================
HOST_IP=$SELECTED_IP

# ==========================================
# Frontend Configuration
# ==========================================
FRONTEND_PORT=5173

# IMPORTANT: For LAN access, these use HOST_IP
VITE_API_SERVER_URL=http://$SELECTED_IP:2030
VITE_AI_SERVER_URL=http://$SELECTED_IP:9999

# ==========================================
# API Server (Go) Configuration
# ==========================================
API_SERVER_PORT=2030
API_SERVER_HOST=0.0.0.0
API_SERVER_READ_TIMEOUT=60
STATUS_DEV=dev

# ==========================================
# AI Server (Python) Configuration
# ==========================================
AI_SERVER_PORT=9999
AI_SERVER_HOST=0.0.0.0

# ==========================================
# Redis Configuration
# ==========================================
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_DB=0

# ==========================================
# Kafka Configuration
# ==========================================
KAFKA_PORT=9092
KAFKA_BOOTSTRAP_SERVERS=kafka:9093
KAFKA_GROUP_ID=vrecom_ai_server_group

# ==========================================
# Kafka UI Configuration
# ==========================================
KAFKA_UI_PORT=8080

# ==========================================
# Prometheus Configuration
# ==========================================
PROMETHEUS_PORT=9090

# ==========================================
# Security Keys
# ==========================================
# WARNING: Change these in production!
JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
SESSION_SECRET=your-super-secret-session-key-change-in-production

# ==========================================
# Admin Portal Configuration
# ==========================================
ADMIN_PORTAL_PORT=3456
API_SERVER_URL=http://localhost:2030
EOF

echo -e "${GREEN}[SUCCESS]${NC} .env file created successfully!"
echo ""

# Ask if user wants to rebuild Docker
echo "===================================================================="
echo "   Next Steps"
echo "===================================================================="
echo ""
echo "To apply changes, you need to rebuild the Docker containers:"
echo ""
echo "  docker-compose down"
echo "  docker-compose build --no-cache frontend"
echo "  docker-compose up -d"
echo ""

read -p "Do you want to rebuild Docker now? (y/n): " REBUILD
if [[ "$REBUILD" =~ ^[Yy]$ ]]; then
    echo ""
    echo -e "${BLUE}[INFO]${NC} Stopping containers..."
    docker-compose down

    echo ""
    echo -e "${BLUE}[INFO]${NC} Rebuilding frontend..."
    docker-compose build --no-cache frontend

    echo ""
    echo -e "${BLUE}[INFO]${NC} Starting containers..."
    docker-compose up -d

    echo ""
    echo -e "${GREEN}[SUCCESS]${NC} Docker containers rebuilt and started!"
fi

echo ""
echo "===================================================================="
echo "   Configuration Complete!"
echo "===================================================================="
echo ""
echo "Your VRecommendation system is now configured for LAN access."
echo ""
echo "Access URLs:"
echo "  Frontend:    http://$SELECTED_IP:5173"
echo "  API Server:  http://$SELECTED_IP:2030"
echo "  AI Server:   http://$SELECTED_IP:9999"
echo "  Kafka UI:    http://$SELECTED_IP:8080"
echo ""
echo -e "${YELLOW}NOTE:${NC} SuperAdmin features are ONLY accessible from localhost!"
echo "      Use Admin Portal (admin-portal/start.sh) on this machine."
echo ""
echo "===================================================================="
echo ""

# Open firewall ports (Linux only)
if [[ "$OSTYPE" != "darwin"* ]]; then
    read -p "Do you want to open firewall ports (requires sudo)? (y/n): " FIREWALL
    if [[ "$FIREWALL" =~ ^[Yy]$ ]]; then
        echo ""
        echo -e "${BLUE}[INFO]${NC} Opening firewall ports..."

        # Try ufw first (Ubuntu/Debian)
        if command -v ufw &> /dev/null; then
            sudo ufw allow 5173/tcp comment "VRecom Frontend"
            sudo ufw allow 2030/tcp comment "VRecom API"
            sudo ufw allow 9999/tcp comment "VRecom AI"
            sudo ufw allow 8080/tcp comment "VRecom Kafka UI"
            echo -e "${GREEN}[SUCCESS]${NC} UFW firewall rules added!"
        # Try firewalld (CentOS/RHEL/Fedora)
        elif command -v firewall-cmd &> /dev/null; then
            sudo firewall-cmd --permanent --add-port=5173/tcp
            sudo firewall-cmd --permanent --add-port=2030/tcp
            sudo firewall-cmd --permanent --add-port=9999/tcp
            sudo firewall-cmd --permanent --add-port=8080/tcp
            sudo firewall-cmd --reload
            echo -e "${GREEN}[SUCCESS]${NC} Firewalld rules added!"
        else
            echo -e "${YELLOW}[WARNING]${NC} No known firewall manager found. Please open ports manually."
        fi
    fi
fi

echo ""
echo "Setup complete!"
