---
# ===========================================
# AI SERVER KAFKA CONSUMER CONFIGURATION
# ===========================================

# Kafka Connection
kafka:
  brokers:
    - kafka:9092
  client_id: 'ai-server-consumer'
  consumer_group: 'ai-recommendation-group'

# Consumer Settings
consumer:
  auto_offset_reset: 'earliest'
  max_poll_records: 500
  session_timeout_ms: 30000
  heartbeat_interval_ms: 3000
  max_poll_interval_ms: 300000  # 5 minutes for AI processing
  enable_auto_commit: false

# Topics to Subscribe
topics:
  user_events: 'user_interactions_events'
  recommendation_requests: 'recommendation_requests'

# AI Model Configuration
model:
  batch_size: 32
  inference_timeout_ms: 30000
  max_recommendations: 20
  feature_window_hours: 168  # 1 week

# Processing
processing:
  worker_threads: 2
  queue_size: 1000
  flush_interval_seconds: 30

# Environment
debug: true
log_level: 'INFO'
...