---
services:
  vrecommendation:
    build: .
    ports:
      - "${HOST_PORT:-2030}:${HOST_PORT:-3000}"
    environment:
      - PORT=${HOST_PORT:-3000}
    volumes:
      - ./logs:/app/logs
    networks:
      - vrecommendation-network
    restart: unless-stopped

networks:
  vrecommendation-network:
    driver: bridge