recommend_system:
  # The type of recommendation system to use
  type: "collaborative_filtering"

  # Configuration for collaborative filtering
  collaborative_filtering:
    # Number of neighbors to consider in the recommendation algorithm
    num_neighbors: 5

    # Similarity metric to use (e.g., 'cosine', 'pearson')
    similarity_metric: "cosine"

  # Configuration for content-based filtering
  content_based_filtering:
    # Features to consider for content-based recommendations
    features:
      - "genre"
      - "director"
      - "actors"
      - "keywords"

  # Configuration for hybrid recommendation system
  hybrid:
    # Weighting factor for combining collaborative and content-based recommendations
    weight_collaborative: 0.7
    weight_content_based: 0.3
