const products = [
    {
        id: 1,
        name: "Sony WH-1000XM5 Wireless Headphones",
        description: "Industry-leading noise canceling with Auto NC Optimizer, exceptional sound quality with DSEE Extreme, 30-hour battery life",
        price: 399.99,
        category: "electronics",
        brand: "Sony",
        stock: 45,
        rating: 4.8,
        image: "https://picsum.photos/seed/product1/400/300"
    },
    {
        id: 2,
        name: "Apple MacBook Pro 14-inch M3",
        description: "M3 chip with 8-core CPU and 10-core GPU, 14.2-inch Liquid Retina XDR display, 16GB RAM, 512GB SSD",
        price: 1999.00,
        category: "electronics",
        brand: "Apple",
        stock: 28,
        rating: 4.9,
        image: "https://picsum.photos/seed/product2/400/300"
    },
    {
        id: 3,
        name: "Samsung 65-inch QLED 4K Smart TV",
        description: "Quantum Dot technology, 4K UHD resolution, HDR10+, Smart TV with Tizen OS, Alexa built-in",
        price: 1299.99,
        category: "electronics",
        brand: "Samsung",
        stock: 15,
        rating: 4.7,
        image: "https://picsum.photos/seed/product3/400/300"
    },
    {
        id: 4,
        name: "Canon EOS R6 Mark II Camera Body",
        description: "24.2MP full-frame sensor, 40 fps continuous shooting, 6K video recording, advanced subject detection AF",
        price: 2499.00,
        category: "electronics",
        brand: "Canon",
        stock: 12,
        rating: 4.9,
        image: "https://picsum.photos/seed/product4/400/300"
    },
    {
        id: 5,
        name: "iPad Pro 12.9-inch M2",
        description: "M2 chip with 8-core CPU, 12.9-inch Liquid Retina XDR display, 256GB storage, Apple Pencil support",
        price: 1199.00,
        category: "electronics",
        brand: "Apple",
        stock: 18,
        rating: 4.8,
        image: "https://picsum.photos/seed/product5/400/300"
    },
    {
        id: 6,
        name: "Bose QuietComfort Ultra Earbuds",
        description: "Premium noise canceling, immersive spatial audio, up to 24 hours battery with case, IPX4 water resistant",
        price: 299.00,
        category: "electronics",
        brand: "Bose",
        stock: 67,
        rating: 4.6,
        image: "https://picsum.photos/seed/product6/400/300"
    },
    {
        id: 7,
        name: "Dell XPS 13 Laptop",
        description: "13th Gen Intel Core i7, 16GB RAM, 512GB SSD, 13.4-inch FHD+ InfinityEdge display",
        price: 1399.00,
        category: "electronics",
        brand: "Dell",
        stock: 22,
        rating: 4.7,
        image: "https://picsum.photos/seed/product7/400/300"
    },
    {
        id: 8,
        name: "LG UltraGear 27-inch Gaming Monitor",
        description: "27-inch QHD IPS display, 144Hz refresh rate, 1ms response time, G-Sync compatible, HDR10",
        price: 449.99,
        category: "electronics",
        brand: "LG",
        stock: 34,
        rating: 4.5,
        image: "https://picsum.photos/seed/product8/400/300"
    },
    {
        id: 9,
        name: "Logitech MX Master 3S Wireless Mouse",
        description: "Ergonomic design, 8000 DPI sensor, quiet clicks, MagSpeed scrolling, multi-device connectivity",
        price: 99.99,
        category: "electronics",
        brand: "Logitech",
        stock: 156,
        rating: 4.8,
        image: "https://picsum.photos/seed/product9/400/300"
    },
    {
        id: 10,
        name: "Kindle Paperwhite E-reader",
        description: "6.8-inch glare-free display, adjustable warm light, waterproof, 16GB storage, weeks of battery",
        price: 139.99,
        category: "electronics",
        brand: "Amazon",
        stock: 89,
        rating: 4.7,
        image: "https://picsum.photos/seed/product10/400/300"
    },
    {
        id: 11,
        name: "GoPro HERO12 Black Action Camera",
        description: "5.3K60 video, 27MP photos, HyperSmooth 6.0 stabilization, waterproof to 33ft, HDR",
        price: 399.99,
        category: "electronics",
        brand: "GoPro",
        stock: 41,
        rating: 4.6,
        image: "https://picsum.photos/seed/product11/400/300"
    },
    {
        id: 12,
        name: "Nintendo Switch OLED Console",
        description: "7-inch OLED screen, enhanced audio, 64GB storage, vibrant colors, tabletop stand",
        price: 349.99,
        category: "electronics",
        brand: "Nintendo",
        stock: 53,
        rating: 4.8,
        image: "https://picsum.photos/seed/product12/400/300"
    },
    {
        id: 13,
        name: "Sony PlayStation 5 Console",
        description: "Ultra-high speed SSD, 4K gaming at 120fps, ray tracing, 3D audio, DualSense controller",
        price: 499.99,
        category: "electronics",
        brand: "Sony",
        stock: 27,
        rating: 4.9,
        image: "https://picsum.photos/seed/product13/400/300"
    },
    {
        id: 14,
        name: "Razer BlackWidow V4 Mechanical Keyboard",
        description: "Green mechanical switches, RGB Chroma lighting, programmable keys, media controls, wrist rest",
        price: 169.99,
        category: "electronics",
        brand: "Razer",
        stock: 78,
        rating: 4.7,
        image: "https://picsum.photos/seed/product14/400/300"
    },
    {
        id: 15,
        name: "Anker PowerCore 20000mAh Power Bank",
        description: "High-capacity portable charger, dual USB ports, fast charging, LED indicator, compact design",
        price: 49.99,
        category: "electronics",
        brand: "Anker",
        stock: 234,
        rating: 4.6,
        image: "https://picsum.photos/seed/product15/400/300"
    },
    {
        id: 16,
        name: "Samsung Galaxy S24 Ultra Smartphone",
        description: "6.8-inch Dynamic AMOLED display, Snapdragon 8 Gen 3, 200MP camera, S Pen included, 5000mAh battery",
        price: 1199.99,
        category: "electronics",
        brand: "Samsung",
        stock: 43,
        rating: 4.8,
        image: "https://picsum.photos/seed/product16/400/300"
    },
    {
        id: 17,
        name: "Apple Watch Series 9 GPS",
        description: "S9 chip, always-on Retina display, advanced health monitoring, ECG, crash detection, water resistant",
        price: 399.00,
        category: "electronics",
        brand: "Apple",
        stock: 61,
        rating: 4.7,
        image: "https://picsum.photos/seed/product17/400/300"
    },
    {
        id: 18,
        name: "DJI Mini 4 Pro Drone",
        description: "4K HDR video, 34-min flight time, omnidirectional obstacle sensing, ActiveTrack 360, lightweight",
        price: 759.00,
        category: "electronics",
        brand: "DJI",
        stock: 19,
        rating: 4.8,
        image: "https://picsum.photos/seed/product18/400/300"
    },
    {
        id: 19,
        name: "Beats Studio Pro Wireless Headphones",
        description: "Personalized spatial audio, lossless USB-C audio, up to 40 hours battery, active noise canceling",
        price: 349.99,
        category: "electronics",
        brand: "Beats",
        stock: 72,
        rating: 4.5,
        image: "https://picsum.photos/seed/product19/400/300"
    },
    {
        id: 20,
        name: "Western Digital 2TB SSD",
        description: "M.2 NVMe internal SSD, up to 7000 MB/s read speed, PCIe Gen4, reliable storage for gaming",
        price: 199.99,
        category: "electronics",
        brand: "Western Digital",
        stock: 145,
        rating: 4.7,
        image: "https://picsum.photos/seed/product20/400/300"
    },
    {
        id: 21,
        name: "TP-Link WiFi 6 Router AX3000",
        description: "Dual-band WiFi 6, up to 3Gbps speeds, OFDMA technology, 4 Gigabit LAN ports, parental controls",
        price: 99.99,
        category: "electronics",
        brand: "TP-Link",
        stock: 112,
        rating: 4.6,
        image: "https://picsum.photos/seed/product21/400/300"
    },
    {
        id: 22,
        name: "Nikon Z6 III Mirrorless Camera",
        description: "24.5MP full-frame sensor, 4K UHD video, in-body image stabilization, dual card slots",
        price: 1996.95,
        category: "electronics",
        brand: "Nikon",
        stock: 15,
        rating: 4.8,
        image: "https://picsum.photos/seed/product22/400/300"
    },
    {
        id: 23,
        name: "Fitbit Charge 6 Fitness Tracker",
        description: "Heart rate monitoring, built-in GPS, sleep tracking, stress management, 7-day battery life",
        price: 159.95,
        category: "electronics",
        brand: "Fitbit",
        stock: 98,
        rating: 4.5,
        image: "https://picsum.photos/seed/product23/400/300"
    },
    {
        id: 24,
        name: "Blue Yeti USB Microphone",
        description: "Professional USB condenser mic, four pickup patterns, mute button, gain control, plug-and-play",
        price: 129.99,
        category: "electronics",
        brand: "Blue",
        stock: 87,
        rating: 4.7,
        image: "https://picsum.photos/seed/product24/400/300"
    },
    {
        id: 25,
        name: "Elgato Stream Deck",
        description: "15 customizable LCD keys, one-touch control for streaming, tactile feedback, plugin ecosystem",
        price: 149.99,
        category: "electronics",
        brand: "Elgato",
        stock: 64,
        rating: 4.8,
        image: "https://picsum.photos/seed/product25/400/300"
    },
    {
        id: 26,
        name: "Sonos One Smart Speaker",
        description: "WiFi streaming, voice control with Alexa and Google Assistant, rich sound, humidity resistant",
        price: 219.00,
        category: "electronics",
        brand: "Sonos",
        stock: 76,
        rating: 4.6,
        image: "https://picsum.photos/seed/product26/400/300"
    },
    {
        id: 27,
        name: "Philips Hue Color Starter Kit",
        description: "4 smart LED bulbs, Hue Bridge, 16 million colors, voice control, app control, automation",
        price: 199.99,
        category: "electronics",
        brand: "Philips",
        stock: 54,
        rating: 4.7,
        image: "https://picsum.photos/seed/product27/400/300"
    },
    {
        id: 28,
        name: "Ring Video Doorbell Pro 2",
        description: "1536p HD video, 3D motion detection, bird's eye view, two-way talk, Alexa compatible",
        price: 249.99,
        category: "electronics",
        brand: "Ring",
        stock: 83,
        rating: 4.5,
        image: "https://picsum.photos/seed/product28/400/300"
    },
    {
        id: 29,
        name: "Microsoft Surface Pro 9",
        description: "12th Gen Intel Core i7, 16GB RAM, 512GB SSD, 13-inch PixelSense touchscreen, 2-in-1 design",
        price: 1599.99,
        category: "electronics",
        brand: "Microsoft",
        stock: 31,
        rating: 4.6,
        image: "https://picsum.photos/seed/product29/400/300"
    },
    {
        id: 30,
        name: "Google Nest Hub Max",
        description: "10-inch HD display, built-in Nest Cam, stereo speakers, Google Assistant, smart home control",
        price: 229.00,
        category: "electronics",
        brand: "Google",
        stock: 67,
        rating: 4.6,
        image: "https://picsum.photos/seed/product30/400/300"
    },
    {
        id: 31,
        name: "Asus ROG Strix Gaming Laptop",
        description: "Intel Core i9, NVIDIA RTX 4070, 32GB RAM, 1TB SSD, 17.3-inch 240Hz display, RGB keyboard",
        price: 2499.99,
        category: "electronics",
        brand: "Asus",
        stock: 18,
        rating: 4.8,
        image: "https://picsum.photos/seed/product31/400/300"
    },
    {
        id: 32,
        name: "Wacom Intuos Pro Digital Drawing Tablet",
        description: "Medium size, 8192 pressure levels, multi-touch surface, wireless connectivity, Pro Pen 2",
        price: 379.95,
        category: "electronics",
        brand: "Wacom",
        stock: 45,
        rating: 4.7,
        image: "https://picsum.photos/seed/product32/400/300"
    },
    {
        id: 33,
        name: "Oculus Quest 3 VR Headset",
        description: "All-in-one VR, 4K+ display, mixed reality experiences, hand tracking, wireless, extensive game library",
        price: 499.99,
        category: "electronics",
        brand: "Meta",
        stock: 38,
        rating: 4.7,
        image: "https://picsum.photos/seed/product33/400/300"
    },
    {
        id: 34,
        name: "SanDisk 512GB SD Card",
        description: "Extreme PRO, UHS-I, read speeds up to 170MB/s, write speeds up to 90MB/s, 4K UHD ready",
        price: 79.99,
        category: "electronics",
        brand: "SanDisk",
        stock: 189,
        rating: 4.8,
        image: "https://picsum.photos/seed/product34/400/300"
    },
    {
        id: 35,
        name: "JBL Flip 6 Portable Speaker",
        description: "Powerful sound, IP67 waterproof and dustproof, 12 hours playtime, PartyBoost compatibility",
        price: 129.95,
        category: "electronics",
        brand: "JBL",
        stock: 142,
        rating: 4.6,
        image: "https://picsum.photos/seed/product35/400/300"
    },
    {
        id: 36,
        name: "Seagate 8TB External Hard Drive",
        description: "USB 3.0, desktop storage, automatic backup, plug-and-play, compatible with PC and Mac",
        price: 159.99,
        category: "electronics",
        brand: "Seagate",
        stock: 96,
        rating: 4.5,
        image: "https://picsum.photos/seed/product36/400/300"
    },
    {
        id: 37,
        name: "Corsair K70 RGB Mechanical Keyboard",
        description: "Cherry MX switches, per-key RGB backlighting, aircraft-grade aluminum frame, media controls",
        price: 179.99,
        category: "electronics",
        brand: "Corsair",
        stock: 71,
        rating: 4.7,
        image: "https://picsum.photos/seed/product37/400/300"
    },
    {
        id: 38,
        name: "HyperX Cloud II Gaming Headset",
        description: "7.1 surround sound, memory foam ear cushions, detachable mic, multi-platform compatibility",
        price: 99.99,
        category: "electronics",
        brand: "HyperX",
        stock: 118,
        rating: 4.7,
        image: "https://picsum.photos/seed/product38/400/300"
    },
    {
        id: 39,
        name: "BenQ PD2700U 4K Monitor",
        description: "27-inch 4K UHD, IPS panel, sRGB and Rec.709 color accuracy, CAD/CAM mode, eye-care technology",
        price: 549.00,
        category: "electronics",
        brand: "BenQ",
        stock: 29,
        rating: 4.6,
        image: "https://picsum.photos/seed/product39/400/300"
    },
    {
        id: 40,
        name: "Apple AirPods Pro 2nd Gen",
        description: "Active noise cancellation, adaptive audio, personalized spatial audio, USB-C charging case",
        price: 249.00,
        category: "electronics",
        brand: "Apple",
        stock: 156,
        rating: 4.8,
        image: "https://picsum.photos/seed/product40/400/300"
    },
    {
        id: 41,
        name: "Yamaha YAS-209 Soundbar",
        description: "DTS Virtual:X, Alexa built-in, wireless subwoofer, Bluetooth streaming, clear voice mode",
        price: 349.95,
        category: "electronics",
        brand: "Yamaha",
        stock: 42,
        rating: 4.6,
        image: "https://picsum.photos/seed/product41/400/300"
    },
    {
        id: 42,
        name: "Netgear Nighthawk Cable Modem",
        description: "DOCSIS 3.1, multi-gig speed, supports plans up to 2Gbps, dual Ethernet ports, compatible",
        price: 199.99,
        category: "electronics",
        brand: "Netgear",
        stock: 68,
        rating: 4.5,
        image: "https://picsum.photos/seed/product42/400/300"
    },
    {
        id: 43,
        name: "Garmin Forerunner 965 GPS Watch",
        description: "AMOLED touchscreen, training readiness, full-color maps, music storage, advanced metrics",
        price: 599.99,
        category: "electronics",
        brand: "Garmin",
        stock: 34,
        rating: 4.8,
        image: "https://picsum.photos/seed/product43/400/300"
    },
    {
        id: 44,
        name: "Rode VideoMic Pro+ Shotgun Mic",
        description: "On-camera microphone, rechargeable battery, safety channel, high-pass filter, automatic power",
        price: 299.00,
        category: "electronics",
        brand: "Rode",
        stock: 52,
        rating: 4.7,
        image: "https://picsum.photos/seed/product44/400/300"
    },
    {
        id: 45,
        name: "Crucial 32GB RAM Kit DDR4",
        description: "2x16GB, 3200MHz, desktop memory, improves responsiveness, plug-and-play installation",
        price: 89.99,
        category: "electronics",
        brand: "Crucial",
        stock: 203,
        rating: 4.7,
        image: "https://picsum.photos/seed/product45/400/300"
    },
    {
        id: 46,
        name: "Acer Predator Gaming Monitor",
        description: "27-inch QHD, 165Hz refresh rate, 0.5ms response time, HDR400, G-Sync compatible",
        price: 399.99,
        category: "electronics",
        brand: "Acer",
        stock: 47,
        rating: 4.6,
        image: "https://picsum.photos/seed/product46/400/300"
    },
    {
        id: 47,
        name: "Sony Alpha a7 IV Camera",
        description: "33MP full-frame sensor, 4K 60p video, 759 phase-detect AF points, 5-axis stabilization",
        price: 2498.00,
        category: "electronics",
        brand: "Sony",
        stock: 21,
        rating: 4.9,
        image: "https://picsum.photos/seed/product47/400/300"
    },
    {
        id: 48,
        name: "Logitech C920 HD Pro Webcam",
        description: "1080p Full HD video, 78-degree field of view, autofocus, dual stereo mics, works with major platforms",
        price: 79.99,
        category: "electronics",
        brand: "Logitech",
        stock: 187,
        rating: 4.6,
        image: "https://picsum.photos/seed/product48/400/300"
    },
    {
        id: 49,
        name: "Amazon Echo Dot 5th Gen",
        description: "Smart speaker with Alexa, improved audio, temperature sensor, tap gestures, eero built-in",
        price: 49.99,
        category: "electronics",
        brand: "Amazon",
        stock: 312,
        rating: 4.5,
        image: "https://picsum.photos/seed/product49/400/300"
    },
    {
        id: 50,
        name: "Roku Streaming Stick 4K",
        description: "4K/HDR/Dolby Vision, voice remote, private listening, quick launch buttons, wireless streaming",
        price: 49.99,
        category: "electronics",
        brand: "Roku",
        stock: 234,
        rating: 4.6,
        image: "https://picsum.photos/seed/product50/400/300"
    },
    {
        id: 51,
        name: "Levi's 501 Original Fit Jeans",
        description: "The original blue jean since 1873. Made with 100% cotton denim, button fly, straight leg fit",
        price: 89.50,
        category: "clothing",
        brand: "Levi's",
        stock: 120,
        rating: 4.6,
        image: "https://picsum.photos/seed/product51/400/300"
    },
    {
        id: 52,
        name: "Nike Air Max 270 Running Shoes",
        description: "Max Air unit for exceptional cushioning, breathable mesh upper, durable rubber outsole",
        price: 150.00,
        category: "clothing",
        brand: "Nike",
        stock: 80,
        rating: 4.7,
        image: "https://picsum.photos/seed/product52/400/300"
    },
    {
        id: 53,
        name: "Adidas Ultraboost 22 Women's Sneakers",
        description: "Energy-returning Boost midsole, Primeknit+ upper, Continental rubber outsole",
        price: 190.00,
        category: "clothing",
        brand: "Adidas",
        stock: 65,
        rating: 4.7,
        image: "https://picsum.photos/seed/product53/400/300"
    },
    {
        id: 54,
        name: "The North Face Thermoball Jacket",
        description: "Synthetic insulation stays warm when wet, water-repellent finish, packable design",
        price: 229.00,
        category: "clothing",
        brand: "The North Face",
        stock: 55,
        rating: 4.6,
        image: "https://picsum.photos/seed/product54/400/300"
    },
    {
        id: 55,
        name: "Patagonia Better Sweater Fleece",
        description: "Soft fleece fabric, quarter-zip pullover, dyed with low-impact process, warm and durable",
        price: 139.00,
        category: "clothing",
        brand: "Patagonia",
        stock: 72,
        rating: 4.8,
        image: "https://picsum.photos/seed/product55/400/300"
    },
    {
        id: 56,
        name: "Columbia Hiking Boots",
        description: "Waterproof leather upper, Omni-Grip non-marking traction rubber, cushioned midsole",
        price: 119.99,
        category: "clothing",
        brand: "Columbia",
        stock: 48,
        rating: 4.5,
        image: "https://picsum.photos/seed/product56/400/300"
    },
    {
        id: 57,
        name: "Under Armour Performance T-Shirt",
        description: "Moisture-wicking fabric, anti-odor technology, 4-way stretch, lightweight and breathable",
        price: 29.99,
        category: "clothing",
        brand: "Under Armour",
        stock: 215,
        rating: 4.4,
        image: "https://picsum.photos/seed/product57/400/300"
    },
    {
        id: 58,
        name: "Carhartt Canvas Work Pants",
        description: "Durable cotton canvas, reinforced knees, multiple tool pockets, relaxed fit",
        price: 64.99,
        category: "clothing",
        brand: "Carhartt",
        stock: 94,
        rating: 4.7,
        image: "https://picsum.photos/seed/product58/400/300"
    },
    {
        id: 59,
        name: "Ray-Ban Aviator Sunglasses",
        description: "Classic metal frame, gradient lenses, 100% UV protection, iconic teardrop shape",
        price: 159.00,
        category: "clothing",
        brand: "Ray-Ban",
        stock: 132,
        rating: 4.6,
        image: "https://picsum.photos/seed/product59/400/300"
    },
    {
        id: 60,
        name: "Tommy Hilfiger Polo Shirt",
        description: "Classic fit, 100% cotton pique, embroidered logo, ribbed collar and cuffs",
        price: 49.50,
        category: "clothing",
        brand: "Tommy Hilfiger",
        stock: 178,
        rating: 4.5,
        image: "https://picsum.photos/seed/product60/400/300"
    },
    {
        id: 61,
        name: "Puma Track Jacket",
        description: "Retro-inspired design, full zip, side pockets, moisture-wicking dryCELL technology",
        price: 65.00,
        category: "clothing",
        brand: "Puma",
        stock: 87,
        rating: 4.4,
        image: "https://picsum.photos/seed/product61/400/300"
    },
    {
        id: 62,
        name: "Hanes ComfortBlend Hoodie",
        description: "Cotton-poly blend, pullover style, kangaroo pocket, ribbed cuffs and hem",
        price: 24.99,
        category: "clothing",
        brand: "Hanes",
        stock: 267,
        rating: 4.3,
        image: "https://picsum.photos/seed/product62/400/300"
    },
    {
        id: 63,
        name: "Reebok Training Shorts",
        description: "Speedwick fabric wicks sweat, mesh panels for ventilation, elastic waistband with drawcord",
        price: 34.99,
        category: "clothing",
        brand: "Reebok",
        stock: 154,
        rating: 4.4,
        image: "https://picsum.photos/seed/product63/400/300"
    },
    {
        id: 64,
        name: "Vans Old Skool Sneakers",
        description: "Low-top lace-up with durable canvas and suede uppers, signature side stripe, waffle outsole",
        price: 65.00,
        category: "clothing",
        brand: "Vans",
        stock: 198,
        rating: 4.6,
        image: "https://picsum.photos/seed/product64/400/300"
    },
    {
        id: 65,
        name: "Champion Reverse Weave Sweatshirt",
        description: "Cut-on-the-cross fabric resists shrinkage, classic crew neck, heavyweight fleece",
        price: 60.00,
        category: "clothing",
        brand: "Champion",
        stock: 112,
        rating: 4.5,
        image: "https://picsum.photos/seed/product65/400/300"
    },
    {
        id: 66,
        name: "Dockers Alpha Khaki Pants",
        description: "Slim tapered fit, stretch fabric, wrinkle-resistant, versatile casual style",
        price: 54.99,
        category: "clothing",
        brand: "Dockers",
        stock: 143,
        rating: 4.4,
        image: "https://picsum.photos/seed/product66/400/300"
    },
    {
        id: 67,
        name: "Calvin Klein Boxer Briefs 3-Pack",
        description: "Cotton stretch fabric, comfortable waistband with logo, classic fit, breathable",
        price: 42.50,
        category: "clothing",
        brand: "Calvin Klein",
        stock: 289,
        rating: 4.6,
        image: "https://picsum.photos/seed/product67/400/300"
    },
    {
        id: 68,
        name: "New Balance 990v5 Running Shoes",
        description: "ENCAP midsole for support and durability, blown rubber outsole, pigskin/mesh upper",
        price: 185.00,
        category: "clothing",
        brand: "New Balance",
        stock: 76,
        rating: 4.7,
        image: "https://picsum.photos/seed/product68/400/300"
    },
    {
        id: 69,
        name: "Timberland 6-Inch Premium Boots",
        description: "Waterproof leather, seam-sealed construction, padded collar, anti-fatigue comfort technology",
        price: 198.00,
        category: "clothing",
        brand: "Timberland",
        stock: 62,
        rating: 4.8,
        image: "https://picsum.photos/seed/product69/400/300"
    },
    {
        id: 70,
        name: "Polo Ralph Lauren Oxford Shirt",
        description: "100% cotton, button-down collar, chest pocket, signature embroidered pony",
        price: 89.50,
        category: "clothing",
        brand: "Ralph Lauren",
        stock: 94,
        rating: 4.6,
        image: "https://picsum.photos/seed/product70/400/300"
    },
    {
        id: 71,
        name: "Converse Chuck Taylor All Star",
        description: "Classic canvas high-top, OrthoLite cushioning, durable rubber outsole, iconic star ankle patch",
        price: 60.00,
        category: "clothing",
        brand: "Converse",
        stock: 234,
        rating: 4.5,
        image: "https://picsum.photos/seed/product71/400/300"
    },
    {
        id: 72,
        name: "Uniqlo Supima Cotton T-Shirt",
        description: "Premium Supima cotton, soft and smooth texture, crew neck, versatile basic",
        price: 14.90,
        category: "clothing",
        brand: "Uniqlo",
        stock: 412,
        rating: 4.4,
        image: "https://picsum.photos/seed/product72/400/300"
    },
    {
        id: 73,
        name: "Skechers Slip-On Walking Shoes",
        description: "Memory Foam insole, flexible sole, easy slip-on design, breathable knit upper",
        price: 64.99,
        category: "clothing",
        brand: "Skechers",
        stock: 167,
        rating: 4.5,
        image: "https://picsum.photos/seed/product73/400/300"
    },
    {
        id: 74,
        name: "Fossil Leather Belt",
        description: "Genuine leather, reversible design, brushed metal buckle, classic style",
        price: 38.00,
        category: "clothing",
        brand: "Fossil",
        stock: 198,
        rating: 4.4,
        image: "https://picsum.photos/seed/product74/400/300"
    },
    {
        id: 75,
        name: "Canada Goose Expedition Parka",
        description: "Premium duck down insulation, Arctic Tech fabric, coyote fur ruff, extreme cold protection",
        price: 1095.00,
        category: "clothing",
        brand: "Canada Goose",
        stock: 23,
        rating: 4.8,
        image: "https://picsum.photos/seed/product75/400/300"
    },
    {
        id: 76,
        name: "Everlane Cashmere Crew Sweater",
        description: "Grade-A cashmere, relaxed fit, ribbed trim, sustainable sourcing",
        price: 100.00,
        category: "clothing",
        brand: "Everlane",
        stock: 67,
        rating: 4.6,
        image: "https://picsum.photos/seed/product76/400/300"
    },
    {
        id: 77,
        name: "Arc'teryx Beta LT Jacket",
        description: "GORE-TEX waterproof/breathable protection, packable hood, lightweight shell, helmet compatible",
        price: 449.00,
        category: "clothing",
        brand: "Arc'teryx",
        stock: 34,
        rating: 4.8,
        image: "https://picsum.photos/seed/product77/400/300"
    },
    {
        id: 78,
        name: "Banana Republic Chinos",
        description: "Slim fit, stretch cotton blend, flat front, classic 5-pocket styling",
        price: 79.50,
        category: "clothing",
        brand: "Banana Republic",
        stock: 102,
        rating: 4.5,
        image: "https://picsum.photos/seed/product78/400/300"
    },
    {
        id: 79,
        name: "J.Crew Merino Wool Sweater",
        description: "Soft merino wool, V-neck design, lightweight warmth, machine washable",
        price: 79.50,
        category: "clothing",
        brand: "J.Crew",
        stock: 88,
        rating: 4.5,
        image: "https://picsum.photos/seed/product79/400/300"
    },
    {
        id: 80,
        name: "Herschel Supply Co. Backpack",
        description: "Classic design, padded laptop sleeve, front pocket, adjustable straps, signature striped lining",
        price: 69.99,
        category: "clothing",
        brand: "Herschel",
        stock: 145,
        rating: 4.6,
        image: "https://picsum.photos/seed/product80/400/300"
    },
    {
        id: 81,
        name: "Sperry Boat Shoes",
        description: "Premium leather, hand-sewn construction, non-marking rubber outsole, 360-degree lacing",
        price: 99.95,
        category: "clothing",
        brand: "Sperry",
        stock: 117,
        rating: 4.5,
        image: "https://picsum.photos/seed/product81/400/300"
    },
    {
        id: 82,
        name: "Lululemon Align Leggings",
        description: "Nulu fabric feels weightless, high-rise fit, hidden pocket, four-way stretch",
        price: 98.00,
        category: "clothing",
        brand: "Lululemon",
        stock: 187,
        rating: 4.7,
        image: "https://picsum.photos/seed/product82/400/300"
    },
    {
        id: 83,
        name: "North Face Denali Fleece",
        description: "Classic Polartec fleece, abrasion overlays, zip-in compatible, reinforced shoulders",
        price: 179.00,
        category: "clothing",
        brand: "The North Face",
        stock: 71,
        rating: 4.7,
        image: "https://picsum.photos/seed/product83/400/300"
    },
    {
        id: 84,
        name: "Oakley Holbrook Sunglasses",
        description: "Plutonite lenses with 100% UV protection, stress-resistant O Matter frame, three-point fit",
        price: 136.00,
        category: "clothing",
        brand: "Oakley",
        stock: 98,
        rating: 4.6,
        image: "https://picsum.photos/seed/product84/400/300"
    },
    {
        id: 85,
        name: "Patagonia Nano Puff Vest",
        description: "PrimaLoft Gold insulation, weather-resistant, packable, lightweight layering piece",
        price: 149.00,
        category: "clothing",
        brand: "Patagonia",
        stock: 84,
        rating: 4.6,
        image: "https://picsum.photos/seed/product85/400/300"
    },
    {
        id: 86,
        name: "Gildan Heavy Cotton T-Shirt",
        description: "100% preshrunk cotton, classic fit, double-needle stitching, tearaway label",
        price: 7.99,
        category: "clothing",
        brand: "Gildan",
        stock: 587,
        rating: 4.2,
        image: "https://picsum.photos/seed/product86/400/300"
    },
    {
        id: 87,
        name: "Crocs Classic Clogs",
        description: "Croslite foam construction, water-friendly, ventilation ports, pivoting heel straps",
        price: 49.99,
        category: "clothing",
        brand: "Crocs",
        stock: 312,
        rating: 4.3,
        image: "https://picsum.photos/seed/product87/400/300"
    },
    {
        id: 88,
        name: "Columbia PFG Fishing Shirt",
        description: "Omni-Shade UPF 50 sun protection, moisture-wicking, vented back, multiple pockets",
        price: 39.99,
        category: "clothing",
        brand: "Columbia",
        stock: 134,
        rating: 4.5,
        image: "https://picsum.photos/seed/product88/400/300"
    },
    {
        id: 89,
        name: "Birkenstock Arizona Sandals",
        description: "Contoured cork footbed, adjustable buckle straps, EVA sole, classic two-strap design",
        price: 99.95,
        category: "clothing",
        brand: "Birkenstock",
        stock: 156,
        rating: 4.7,
        image: "https://picsum.photos/seed/product89/400/300"
    },
    {
        id: 90,
        name: "Fjallraven Kanken Backpack",
        description: "Durable Vinylon F fabric, classic square shape, padded shoulder straps, front zippered pocket",
        price: 80.00,
        category: "clothing",
        brand: "Fjallraven",
        stock: 123,
        rating: 4.6,
        image: "https://picsum.photos/seed/product90/400/300"
    },
    {
        id: 91,
        name: "Dickies Work Shirt",
        description: "Short sleeve button-down, moisture-wicking, stain release, two chest pockets",
        price: 32.99,
        category: "clothing",
        brand: "Dickies",
        stock: 198,
        rating: 4.4,
        image: "https://picsum.photos/seed/product91/400/300"
    },
    {
        id: 92,
        name: "Asics Gel-Kayano Running Shoes",
        description: "FlyteFoam cushioning, Dynamic DuoMax support, AHAR rubber outsole, breathable mesh upper",
        price: 160.00,
        category: "clothing",
        brand: "Asics",
        stock: 91,
        rating: 4.7,
        image: "https://picsum.photos/seed/product92/400/300"
    },
    {
        id: 93,
        name: "Brooks Ghost 15 Running Shoes",
        description: "Soft cushioning, smooth transitions, DNA LOFT crash pad, Segmented Crash Pad",
        price: 140.00,
        category: "clothing",
        brand: "Brooks",
        stock: 103,
        rating: 4.7,
        image: "https://picsum.photos/seed/product93/400/300"
    },
    {
        id: 94,
        name: "Merrell Moab 2 Hiking Boots",
        description: "Suede leather and mesh upper, Vibram outsole, contoured footbed, breathable waterproof membrane",
        price: 134.95,
        category: "clothing",
        brand: "Merrell",
        stock: 78,
        rating: 4.6,
        image: "https://picsum.photos/seed/product94/400/300"
    },
    {
        id: 95,
        name: "Smartwool Merino Wool Socks",
        description: "Merino wool blend, cushioned footbed, arch support, naturally odor-resistant",
        price: 24.95,
        category: "clothing",
        brand: "Smartwool",
        stock: 267,
        rating: 4.6,
        image: "https://picsum.photos/seed/product95/400/300"
    },
    {
        id: 96,
        name: "Marmot PreCip Rain Jacket",
        description: "Waterproof breathable NanoPro, packable into pocket, adjustable hood, pit zips",
        price: 100.00,
        category: "clothing",
        brand: "Marmot",
        stock: 67,
        rating: 4.5,
        image: "https://picsum.photos/seed/product96/400/300"
    },
    {
        id: 97,
        name: "Outdoor Research Sun Hat",
        description: "UPF 50+ sun protection, moisture-wicking TransAction headband, wide brim, adjustable chin cord",
        price: 34.95,
        category: "clothing",
        brand: "Outdoor Research",
        stock: 142,
        rating: 4.5,
        image: "https://picsum.photos/seed/product97/400/300"
    },
    {
        id: 98,
        name: "Kuhl Radikl Pants",
        description: "Lightweight, quick-dry nylon, DWR finish, nine pockets, articulated knees, gusseted crotch",
        price: 89.00,
        category: "clothing",
        brand: "Kuhl",
        stock: 73,
        rating: 4.7,
        image: "https://picsum.photos/seed/product98/400/300"
    },
    {
        id: 99,
        name: "prAna Stretch Zion Pants",
        description: "Durable stretch nylon, quick-dry, water-repellent, roll-up leg snaps, standard fit",
        price: 79.00,
        category: "clothing",
        brand: "prAna",
        stock: 96,
        rating: 4.6,
        image: "https://picsum.photos/seed/product99/400/300"
    },
    {
        id: 100,
        name: "Darn Tough Hiking Socks",
        description: "Merino wool, seamless construction, unconditional lifetime guarantee, cushioned sole",
        price: 26.95,
        category: "clothing",
        brand: "Darn Tough",
        stock: 234,
        rating: 4.8,
        image: "https://picsum.photos/seed/product100/400/300"
    },
    {
        id: 101,
        name: "Atomic Habits by James Clear",
        description: "An Easy & Proven Way to Build Good Habits & Break Bad Ones. #1 New York Times bestseller",
        price: 16.99,
        category: "books",
        brand: "Penguin Random House",
        stock: 250,
        rating: 4.8,
        image: "https://picsum.photos/seed/product101/400/300"
    },
    {
        id: 102,
        name: "The Psychology of Money by Morgan Housel",
        description: "Timeless lessons on wealth, greed, and happiness. Wall Street Journal bestseller",
        price: 14.99,
        category: "books",
        brand: "Harriman House",
        stock: 180,
        rating: 4.7,
        image: "https://picsum.photos/seed/product102/400/300"
    },
    {
        id: 103,
        name: "Educated: A Memoir by Tara Westover",
        description: "A remarkable story of a woman's quest for knowledge. New York Times bestseller",
        price: 18.00,
        category: "books",
        brand: "Random House",
        stock: 140,
        rating: 4.8,
        image: "https://picsum.photos/seed/product103/400/300"
    },
    {
        id: 104,
        name: "Sapiens by Yuval Noah Harari",
        description: "A Brief History of Humankind. International bestseller exploring human evolution",
        price: 22.99,
        category: "books",
        brand: "Harper",
        stock: 167,
        rating: 4.6,
        image: "https://picsum.photos/seed/product104/400/300"
    },
    {
        id: 105,
        name: "The Midnight Library by Matt Haig",
        description: "Between life and death, a library filled with infinite possibilities and second chances",
        price: 17.00,
        category: "books",
        brand: "Viking",
        stock: 203,
        rating: 4.5,
        image: "https://picsum.photos/seed/product105/400/300"
    },
    {
        id: 106,
        name: "The 7 Habits of Highly Effective People",
        description: "Stephen Covey's classic guide to personal and professional effectiveness",
        price: 19.99,
        category: "books",
        brand: "Simon & Schuster",
        stock: 187,
        rating: 4.7,
        image: "https://picsum.photos/seed/product106/400/300"
    },
    {
        id: 107,
        name: "Where the Crawdads Sing by Delia Owens",
        description: "A mystery, a coming-of-age tale, and a love story set in the marshes of North Carolina",
        price: 16.99,
        category: "books",
        brand: "Putnam",
        stock: 234,
        rating: 4.7,
        image: "https://picsum.photos/seed/product107/400/300"
    },
    {
        id: 108,
        name: "The Subtle Art of Not Giving a F*ck",
        description: "Mark Manson's counterintuitive approach to living a good life",
        price: 15.99,
        category: "books",
        brand: "HarperOne",
        stock: 198,
        rating: 4.4,
        image: "https://picsum.photos/seed/product108/400/300"
    },
    {
        id: 109,
        name: "1984 by George Orwell",
        description: "A dystopian masterpiece about totalitarianism and surveillance",
        price: 13.99,
        category: "books",
        brand: "Signet Classic",
        stock: 312,
        rating: 4.8,
        image: "https://picsum.photos/seed/product109/400/300"
    },
    {
        id: 110,
        name: "Project Hail Mary by Andy Weir",
        description: "A lone astronaut's mission to save Earth from an extinction-level threat",
        price: 18.99,
        category: "books",
        brand: "Ballantine Books",
        stock: 156,
        rating: 4.8,
        image: "https://picsum.photos/seed/product110/400/300"
    },
    {
        id: 111,
        name: "Thinking, Fast and Slow by Daniel Kahneman",
        description: "Nobel Prize winner's groundbreaking exploration of the two systems that drive decision-making",
        price: 20.00,
        category: "books",
        brand: "Farrar, Straus and Giroux",
        stock: 143,
        rating: 4.6,
        image: "https://picsum.photos/seed/product111/400/300"
    },
    {
        id: 112,
        name: "The Alchemist by Paulo Coelho",
        description: "A magical tale about following your dreams and finding your destiny",
        price: 14.99,
        category: "books",
        brand: "HarperOne",
        stock: 267,
        rating: 4.7,
        image: "https://picsum.photos/seed/product112/400/300"
    },
    {
        id: 113,
        name: "Dune by Frank Herbert",
        description: "Epic science fiction masterpiece set on the desert planet Arrakis",
        price: 19.99,
        category: "books",
        brand: "Ace",
        stock: 189,
        rating: 4.8,
        image: "https://picsum.photos/seed/product113/400/300"
    },
    {
        id: 114,
        name: "The Four Agreements by Don Miguel Ruiz",
        description: "Practical guide to personal freedom based on ancient Toltec wisdom",
        price: 12.95,
        category: "books",
        brand: "Amber-Allen Publishing",
        stock: 223,
        rating: 4.7,
        image: "https://picsum.photos/seed/product114/400/300"
    },
    {
        id: 115,
        name: "The Great Gatsby by F. Scott Fitzgerald",
        description: "Classic American novel of the Jazz Age exploring themes of wealth and love",
        price: 11.99,
        category: "books",
        brand: "Scribner",
        stock: 345,
        rating: 4.5,
        image: "https://picsum.photos/seed/product115/400/300"
    },
    {
        id: 116,
        name: "Can't Hurt Me by David Goggins",
        description: "Master Your Mind and Defy the Odds. Memoir and self-help guide from Navy SEAL",
        price: 17.99,
        category: "books",
        brand: "Lioncrest Publishing",
        stock: 178,
        rating: 4.8,
        image: "https://picsum.photos/seed/product116/400/300"
    },
    {
        id: 117,
        name: "The Silent Patient by Alex Michaelides",
        description: "Psychological thriller about a woman who stops speaking after shooting her husband",
        price: 16.99,
        category: "books",
        brand: "Celadon Books",
        stock: 201,
        rating: 4.5,
        image: "https://picsum.photos/seed/product117/400/300"
    },
    {
        id: 118,
        name: "Becoming by Michelle Obama",
        description: "Intimate memoir by former First Lady of the United States",
        price: 19.99,
        category: "books",
        brand: "Crown",
        stock: 167,
        rating: 4.9,
        image: "https://picsum.photos/seed/product118/400/300"
    },
    {
        id: 119,
        name: "The Power of Now by Eckhart Tolle",
        description: "Spiritual guide to living in the present moment",
        price: 15.99,
        category: "books",
        brand: "New World Library",
        stock: 189,
        rating: 4.6,
        image: "https://picsum.photos/seed/product119/400/300"
    },
    {
        id: 120,
        name: "The Hobbit by J.R.R. Tolkien",
        description: "Classic fantasy adventure of Bilbo Baggins and his unexpected journey",
        price: 14.99,
        category: "books",
        brand: "Mariner Books",
        stock: 234,
        rating: 4.8,
        image: "https://picsum.photos/seed/product120/400/300"
    },
    {
        id: 121,
        name: "How to Win Friends and Influence People",
        description: "Dale Carnegie's timeless bestseller on human relations and communication",
        price: 17.00,
        category: "books",
        brand: "Pocket Books",
        stock: 198,
        rating: 4.7,
        image: "https://picsum.photos/seed/product121/400/300"
    },
    {
        id: 122,
        name: "Born a Crime by Trevor Noah",
        description: "Stories from a South African Childhood by The Daily Show host",
        price: 17.00,
        category: "books",
        brand: "Spiegel & Grau",
        stock: 156,
        rating: 4.8,
        image: "https://picsum.photos/seed/product122/400/300"
    },
    {
        id: 123,
        name: "Rich Dad Poor Dad by Robert Kiyosaki",
        description: "What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not",
        price: 16.95,
        category: "books",
        brand: "Plata Publishing",
        stock: 223,
        rating: 4.6,
        image: "https://picsum.photos/seed/product123/400/300"
    },
    {
        id: 124,
        name: "The Book Thief by Markus Zusak",
        description: "Moving story narrated by Death, set in Nazi Germany",
        price: 15.99,
        category: "books",
        brand: "Knopf",
        stock: 178,
        rating: 4.7,
        image: "https://picsum.photos/seed/product124/400/300"
    },
    {
        id: 125,
        name: "Man's Search for Meaning by Viktor Frankl",
        description: "Holocaust survivor's profound exploration of finding purpose in suffering",
        price: 13.99,
        category: "books",
        brand: "Beacon Press",
        stock: 267,
        rating: 4.8,
        image: "https://picsum.photos/seed/product125/400/300"
    },
    {
        id: 126,
        name: "The Lean Startup by Eric Ries",
        description: "How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses",
        price: 17.00,
        category: "books",
        brand: "Currency",
        stock: 143,
        rating: 4.5,
        image: "https://picsum.photos/seed/product126/400/300"
    },
    {
        id: 127,
        name: "The Road by Cormac McCarthy",
        description: "Pulitzer Prize-winning post-apocalyptic novel of a father and son's journey",
        price: 16.00,
        category: "books",
        brand: "Vintage",
        stock: 134,
        rating: 4.3,
        image: "https://picsum.photos/seed/product127/400/300"
    },
    {
        id: 128,
        name: "The 5 AM Club by Robin Sharma",
        description: "Own Your Morning. Elevate Your Life. Productivity and self-improvement guide",
        price: 18.99,
        category: "books",
        brand: "HarperCollins",
        stock: 189,
        rating: 4.4,
        image: "https://picsum.photos/seed/product128/400/300"
    },
    {
        id: 129,
        name: "Harry Potter and the Sorcerer's Stone",
        description: "The magical beginning of Harry Potter's journey at Hogwarts",
        price: 12.99,
        category: "books",
        brand: "Scholastic",
        stock: 412,
        rating: 4.9,
        image: "https://picsum.photos/seed/product129/400/300"
    },
    {
        id: 130,
        name: "Deep Work by Cal Newport",
        description: "Rules for Focused Success in a Distracted World",
        price: 17.00,
        category: "books",
        brand: "Grand Central Publishing",
        stock: 167,
        rating: 4.6,
        image: "https://picsum.photos/seed/product130/400/300"
    },
    {
        id: 131,
        name: "The Catcher in the Rye by J.D. Salinger",
        description: "Classic coming-of-age novel following Holden Caulfield in New York City",
        price: 14.99,
        category: "books",
        brand: "Little, Brown",
        stock: 256,
        rating: 4.3,
        image: "https://picsum.photos/seed/product131/400/300"
    },
    {
        id: 132,
        name: "Good to Great by Jim Collins",
        description: "Why Some Companies Make the Leap and Others Don't. Business bestseller",
        price: 19.99,
        category: "books",
        brand: "HarperBusiness",
        stock: 134,
        rating: 4.5,
        image: "https://picsum.photos/seed/product132/400/300"
    },
    {
        id: 133,
        name: "The Hunger Games by Suzanne Collins",
        description: "Dystopian thriller about survival in a televised death match",
        price: 14.99,
        category: "books",
        brand: "Scholastic",
        stock: 298,
        rating: 4.6,
        image: "https://picsum.photos/seed/product133/400/300"
    },
    {
        id: 134,
        name: "Ikigai by Héctor García and Francesc Miralles",
        description: "The Japanese Secret to a Long and Happy Life",
        price: 15.99,
        category: "books",
        brand: "Penguin Books",
        stock: 178,
        rating: 4.5,
        image: "https://picsum.photos/seed/product134/400/300"
    },
    {
        id: 135,
        name: "Steve Jobs by Walter Isaacson",
        description: "Comprehensive biography of Apple's visionary co-founder",
        price: 20.00,
        category: "books",
        brand: "Simon & Schuster",
        stock: 123,
        rating: 4.7,
        image: "https://picsum.photos/seed/product135/400/300"
    },
    {
        id: 136,
        name: "To Kill a Mockingbird by Harper Lee",
        description: "Pulitzer Prize-winning novel about racial injustice in the American South",
        price: 13.99,
        category: "books",
        brand: "Harper Perennial",
        stock: 289,
        rating: 4.8,
        image: "https://picsum.photos/seed/product136/400/300"
    },
    {
        id: 137,
        name: "The Outsiders by S.E. Hinton",
        description: "Classic coming-of-age story about Greasers and Socs in 1960s Oklahoma",
        price: 12.99,
        category: "books",
        brand: "Penguin Books",
        stock: 234,
        rating: 4.7,
        image: "https://picsum.photos/seed/product137/400/300"
    },
    {
        id: 138,
        name: "Shoe Dog by Phil Knight",
        description: "Memoir by Nike founder about building one of the world's most iconic brands",
        price: 18.00,
        category: "books",
        brand: "Scribner",
        stock: 156,
        rating: 4.7,
        image: "https://picsum.photos/seed/product138/400/300"
    },
    {
        id: 139,
        name: "The Da Vinci Code by Dan Brown",
        description: "Thrilling mystery involving secret societies and religious history",
        price: 16.99,
        category: "books",
        brand: "Anchor",
        stock: 201,
        rating: 4.2,
        image: "https://picsum.photos/seed/product139/400/300"
    },
    {
        id: 140,
        name: "The Subtle Body by Stefanie Syman",
        description: "The Story of Yoga in America - comprehensive history",
        price: 19.99,
        category: "books",
        brand: "Farrar, Straus and Giroux",
        stock: 89,
        rating: 4.4,
        image: "https://picsum.photos/seed/product140/400/300"
    },
    {
        id: 141,
        name: "Lord of the Flies by William Golding",
        description: "Allegorical novel about a group of boys stranded on an uninhabited island",
        price: 12.99,
        category: "books",
        brand: "Penguin Books",
        stock: 267,
        rating: 4.4,
        image: "https://picsum.photos/seed/product141/400/300"
    },
    {
        id: 142,
        name: "The Intelligent Investor by Benjamin Graham",
        description: "Definitive book on value investing with updated commentary",
        price: 24.99,
        category: "books",
        brand: "Harper Business",
        stock: 112,
        rating: 4.7,
        image: "https://picsum.photos/seed/product142/400/300"
    },
    {
        id: 143,
        name: "Pride and Prejudice by Jane Austen",
        description: "Classic romance novel set in Georgian England",
        price: 11.99,
        category: "books",
        brand: "Penguin Classics",
        stock: 312,
        rating: 4.7,
        image: "https://picsum.photos/seed/product143/400/300"
    },
    {
        id: 144,
        name: "The Giver by Lois Lowry",
        description: "Dystopian novel about a seemingly perfect society without pain or suffering",
        price: 10.99,
        category: "books",
        brand: "Houghton Mifflin Harcourt",
        stock: 289,
        rating: 4.5,
        image: "https://picsum.photos/seed/product144/400/300"
    },
    {
        id: 145,
        name: "Freakonomics by Steven Levitt",
        description: "A Rogue Economist Explores the Hidden Side of Everything",
        price: 16.99,
        category: "books",
        brand: "William Morrow",
        stock: 143,
        rating: 4.3,
        image: "https://picsum.photos/seed/product145/400/300"
    },
    {
        id: 146,
        name: "Outliers by Malcolm Gladwell",
        description: "The Story of Success - examining what makes high-achievers different",
        price: 17.99,
        category: "books",
        brand: "Back Bay Books",
        stock: 167,
        rating: 4.6,
        image: "https://picsum.photos/seed/product146/400/300"
    },
    {
        id: 147,
        name: "The Fault in Our Stars by John Green",
        description: "Heartbreaking love story of two teenagers battling cancer",
        price: 14.99,
        category: "books",
        brand: "Dutton Books",
        stock: 234,
        rating: 4.6,
        image: "https://picsum.photos/seed/product147/400/300"
    },
    {
        id: 148,
        name: "The Lord of the Rings by J.R.R. Tolkien",
        description: "Epic fantasy trilogy in one volume - the ultimate quest to destroy the One Ring",
        price: 35.00,
        category: "books",
        brand: "Mariner Books",
        stock: 98,
        rating: 4.9,
        image: "https://picsum.photos/seed/product148/400/300"
    },
    {
        id: 149,
        name: "Mindset by Carol Dweck",
        description: "The New Psychology of Success - growth mindset vs fixed mindset",
        price: 17.00,
        category: "books",
        brand: "Ballantine Books",
        stock: 178,
        rating: 4.6,
        image: "https://picsum.photos/seed/product149/400/300"
    },
    {
        id: 150,
        name: "The Picture of Dorian Gray by Oscar Wilde",
        description: "Gothic philosophical novel about a man who remains young while his portrait ages",
        price: 12.99,
        category: "books",
        brand: "Dover Publications",
        stock: 198,
        rating: 4.5,
        image: "https://picsum.photos/seed/product150/400/300"
    },
    {
        id: 151,
        name: "KitchenAid Artisan Stand Mixer",
        description: "5-quart stainless steel bowl, 10-speed slide control, 325-watt motor, includes attachments",
        price: 429.99,
        category: "home",
        brand: "KitchenAid",
        stock: 35,
        rating: 4.9,
        image: "https://picsum.photos/seed/product151/400/300"
    },
    {
        id: 152,
        name: "Instant Pot Duo 7-in-1 Pressure Cooker",
        description: "6-quart capacity, pressure cooker, slow cooker, rice cooker, steamer, saute, yogurt maker",
        price: 99.95,
        category: "home",
        brand: "Instant Pot",
        stock: 95,
        rating: 4.7,
        image: "https://picsum.photos/seed/product152/400/300"
    },
    {
        id: 153,
        name: "Dyson V15 Detect Cordless Vacuum",
        description: "Laser detect technology, LCD screen, 60 minutes run time, HEPA filtration",
        price: 649.99,
        category: "home",
        brand: "Dyson",
        stock: 22,
        rating: 4.7,
        image: "https://picsum.photos/seed/product153/400/300"
    },
    {
        id: 154,
        name: "Nespresso VertuoPlus Coffee Maker",
        description: "One-touch brewing, centrifusion technology, 40 oz water tank, used capsule container",
        price: 179.95,
        category: "home",
        brand: "Nespresso",
        stock: 67,
        rating: 4.6,
        image: "https://picsum.photos/seed/product154/400/300"
    },
    {
        id: 155,
        name: "Cuisinart Food Processor",
        description: "14-cup capacity, 720-watt motor, stainless steel blade, large feed tube",
        price: 199.00,
        category: "home",
        brand: "Cuisinart",
        stock: 48,
        rating: 4.7,
        image: "https://picsum.photos/seed/product155/400/300"
    },
    {
        id: 156,
        name: "iRobot Roomba j7+ Robot Vacuum",
        description: "Self-emptying, smart mapping, obstacle avoidance, voice control, pet-friendly",
        price: 799.99,
        category: "home",
        brand: "iRobot",
        stock: 31,
        rating: 4.6,
        image: "https://picsum.photos/seed/product156/400/300"
    },
    {
        id: 157,
        name: "Vitamix E310 Explorian Blender",
        description: "48 oz container, variable speed control, aircraft-grade stainless steel blades, 10-year warranty",
        price: 349.95,
        category: "home",
        brand: "Vitamix",
        stock: 43,
        rating: 4.8,
        image: "https://picsum.photos/seed/product157/400/300"
    },
    {
        id: 158,
        name: "Ninja Foodi Air Fryer Oven",
        description: "8-in-1 functionality, air fry, roast, broil, dehydrate, flip-away storage, 1800 watts",
        price: 229.99,
        category: "home",
        brand: "Ninja",
        stock: 56,
        rating: 4.7,
        image: "https://picsum.photos/seed/product158/400/300"
    },
    {
        id: 159,
        name: "Breville Barista Express Espresso Machine",
        description: "Built-in grinder, 15-bar Italian pump, precise espresso extraction, milk frother",
        price: 699.95,
        category: "home",
        brand: "Breville",
        stock: 28,
        rating: 4.8,
        image: "https://picsum.photos/seed/product159/400/300"
    },
    {
        id: 160,
        name: "Keurig K-Elite Coffee Maker",
        description: "Strong brew button, iced coffee setting, 75 oz reservoir, quiet brew technology",
        price: 169.99,
        category: "home",
        brand: "Keurig",
        stock: 89,
        rating: 4.5,
        image: "https://picsum.photos/seed/product160/400/300"
    },
    {
        id: 161,
        name: "Lodge Cast Iron Skillet 12-inch",
        description: "Pre-seasoned, versatile cooking, oven safe, induction compatible, lifetime durability",
        price: 34.90,
        category: "home",
        brand: "Lodge",
        stock: 234,
        rating: 4.8,
        image: "https://picsum.photos/seed/product161/400/300"
    },
    {
        id: 162,
        name: "All-Clad D3 Stainless Cookware Set",
        description: "10-piece set, tri-ply construction, induction compatible, dishwasher safe, made in USA",
        price: 799.95,
        category: "home",
        brand: "All-Clad",
        stock: 19,
        rating: 4.9,
        image: "https://picsum.photos/seed/product162/400/300"
    },
    {
        id: 163,
        name: "Shark Navigator Upright Vacuum",
        description: "HEPA filter, swivel steering, lift-away pod, pet power brush, bagless",
        price: 199.99,
        category: "home",
        brand: "Shark",
        stock: 72,
        rating: 4.6,
        image: "https://picsum.photos/seed/product163/400/300"
    },
    {
        id: 164,
        name: "Hamilton Beach Slow Cooker",
        description: "6-quart capacity, programmable timer, probe thermometer, dishwasher-safe stoneware",
        price: 49.99,
        category: "home",
        brand: "Hamilton Beach",
        stock: 143,
        rating: 4.4,
        image: "https://picsum.photos/seed/product164/400/300"
    },
    {
        id: 165,
        name: "OXO Good Grips Kitchen Utensil Set",
        description: "15-piece set, non-slip handles, heat-resistant silicone, dishwasher safe",
        price: 79.99,
        category: "home",
        brand: "OXO",
        stock: 187,
        rating: 4.7,
        image: "https://picsum.photos/seed/product165/400/300"
    },
    {
        id: 166,
        name: "Pyrex Glass Food Storage Set",
        description: "18-piece set, BPA-free lids, microwave and dishwasher safe, stackable design",
        price: 39.99,
        category: "home",
        brand: "Pyrex",
        stock: 267,
        rating: 4.6,
        image: "https://picsum.photos/seed/product166/400/300"
    },
    {
        id: 167,
        name: "Bed Bath Beyond Towel Set",
        description: "6-piece Turkish cotton towels, quick-dry, soft and absorbent, machine washable",
        price: 59.99,
        category: "home",
        brand: "Bed Bath Beyond",
        stock: 156,
        rating: 4.5,
        image: "https://picsum.photos/seed/product167/400/300"
    },
    {
        id: 168,
        name: "Casper Memory Foam Pillow",
        description: "Adaptive comfort, breathable design, removable washable cover, standard size",
        price: 89.00,
        category: "home",
        brand: "Casper",
        stock: 98,
        rating: 4.4,
        image: "https://picsum.photos/seed/product168/400/300"
    },
    {
        id: 169,
        name: "Brooklinen Luxe Sheet Set",
        description: "Queen size, 480 thread count sateen, 100% long-staple cotton, deep pockets",
        price: 139.00,
        category: "home",
        brand: "Brooklinen",
        stock: 87,
        rating: 4.7,
        image: "https://picsum.photos/seed/product169/400/300"
    },
    {
        id: 170,
        name: "Purple Mattress Queen",
        description: "Gel-flex grid technology, pressure relief, temperature neutral, 10-year warranty",
        price: 1299.00,
        category: "home",
        brand: "Purple",
        stock: 15,
        rating: 4.6,
        image: "https://picsum.photos/seed/product170/400/300"
    },
    {
        id: 171,
        name: "Honeywell HPA300 Air Purifier",
        description: "True HEPA filtration, covers large rooms, allergen reducer, activated carbon pre-filter",
        price: 249.99,
        category: "home",
        brand: "Honeywell",
        stock: 63,
        rating: 4.6,
        image: "https://picsum.photos/seed/product171/400/300"
    },
    {
        id: 172,
        name: "Bissell CrossWave Pet Pro",
        description: "Multi-surface wet dry vacuum, two-tank system, tangle-free brush roll, pet-friendly",
        price: 329.99,
        category: "home",
        brand: "Bissell",
        stock: 48,
        rating: 4.5,
        image: "https://picsum.photos/seed/product172/400/300"
    },
    {
        id: 173,
        name: "Calphalon Nonstick Cookware Set",
        description: "10-piece set, hard-anodized aluminum, stay-cool handles, dishwasher safe",
        price: 299.99,
        category: "home",
        brand: "Calphalon",
        stock: 54,
        rating: 4.6,
        image: "https://picsum.photos/seed/product173/400/300"
    },
    {
        id: 174,
        name: "Wusthof Classic Knife Set",
        description: "7-piece knife block set, German steel, precision-forged, full tang, lifetime warranty",
        price: 499.95,
        category: "home",
        brand: "Wusthof",
        stock: 32,
        rating: 4.9,
        image: "https://picsum.photos/seed/product174/400/300"
    },
    {
        id: 175,
        name: "Rubbermaid FreshWorks Produce Saver",
        description: "3-piece set, FreshVent technology, CrispTray design, keeps produce fresh longer",
        price: 34.99,
        category: "home",
        brand: "Rubbermaid",
        stock: 178,
        rating: 4.5,
        image: "https://picsum.photos/seed/product175/400/300"
    },
    {
        id: 176,
        name: "Thermos Stainless King Travel Mug",
        description: "16 oz capacity, vacuum insulated, keeps hot 7 hours or cold 18 hours, leak-proof lid",
        price: 24.99,
        category: "home",
        brand: "Thermos",
        stock: 298,
        rating: 4.6,
        image: "https://picsum.photos/seed/product176/400/300"
    },
    {
        id: 177,
        name: "Simplehuman Sensor Trash Can",
        description: "13-gallon, voice and motion sensor, custom fit liners, fingerprint-proof",
        price: 179.99,
        category: "home",
        brand: "Simplehuman",
        stock: 67,
        rating: 4.6,
        image: "https://picsum.photos/seed/product177/400/300"
    },
    {
        id: 178,
        name: "Lasko Oscillating Tower Fan",
        description: "42-inch tower fan, 3 speed settings, widespread oscillation, space-saving design",
        price: 59.99,
        category: "home",
        brand: "Lasko",
        stock: 123,
        rating: 4.4,
        image: "https://picsum.photos/seed/product178/400/300"
    },
    {
        id: 179,
        name: "Black+Decker Handheld Vacuum",
        description: "Cordless lithium, cyclonic action, crevice tool and brush, washable filter",
        price: 49.99,
        category: "home",
        brand: "Black+Decker",
        stock: 187,
        rating: 4.3,
        image: "https://picsum.photos/seed/product179/400/300"
    },
    {
        id: 180,
        name: "Vornado Whole Room Heater",
        description: "Advanced safety features, adjustable thermostat, tip-over protection, 5-year warranty",
        price: 89.99,
        category: "home",
        brand: "Vornado",
        stock: 94,
        rating: 4.5,
        image: "https://picsum.photos/seed/product180/400/300"
    },
    {
        id: 181,
        name: "Ruggable Washable Area Rug",
        description: "5x7 feet, machine washable cover, non-slip rug pad, stain resistant",
        price: 249.00,
        category: "home",
        brand: "Ruggable",
        stock: 43,
        rating: 4.5,
        image: "https://picsum.photos/seed/product181/400/300"
    },
    {
        id: 182,
        name: "Umbra Prisma Picture Frame Set",
        description: "6-piece geometric wire frames, various sizes, floating design, includes clips",
        price: 39.99,
        category: "home",
        brand: "Umbra",
        stock: 156,
        rating: 4.4,
        image: "https://picsum.photos/seed/product182/400/300"
    },
    {
        id: 183,
        name: "Threshold Textured Throw Blanket",
        description: "50x60 inches, chunky knit design, soft and cozy, machine washable",
        price: 34.99,
        category: "home",
        brand: "Threshold",
        stock: 198,
        rating: 4.3,
        image: "https://picsum.photos/seed/product183/400/300"
    },
    {
        id: 184,
        name: "mDesign Storage Organizer Bins",
        description: "Set of 4, clear plastic, built-in handles, stackable, pantry organization",
        price: 29.99,
        category: "home",
        brand: "mDesign",
        stock: 234,
        rating: 4.5,
        image: "https://picsum.photos/seed/product184/400/300"
    },
    {
        id: 185,
        name: "Brightroom 3-Tier Rolling Cart",
        description: "Metal mesh baskets, smooth-rolling wheels, handle for easy movement, versatile storage",
        price: 39.99,
        category: "home",
        brand: "Brightroom",
        stock: 112,
        rating: 4.4,
        image: "https://picsum.photos/seed/product185/400/300"
    },
    {
        id: 186,
        name: "Levoit Core 300 Air Purifier",
        description: "True HEPA filter, quiet operation, covers 215 sq ft, 3-stage filtration",
        price: 99.99,
        category: "home",
        brand: "Levoit",
        stock: 134,
        rating: 4.7,
        image: "https://picsum.photos/seed/product186/400/300"
    },
    {
        id: 187,
        name: "Cuisinart Toaster Oven Broiler",
        description: "0.6 cubic foot capacity, toast, bake, broil, convenient auto-shutoff",
        price: 99.99,
        category: "home",
        brand: "Cuisinart",
        stock: 76,
        rating: 4.5,
        image: "https://picsum.photos/seed/product187/400/300"
    },
    {
        id: 188,
        name: "Zojirushi Rice Cooker",
        description: "5.5-cup capacity, neuro fuzzy logic, multiple cooking settings, keep warm function",
        price: 189.99,
        category: "home",
        brand: "Zojirushi",
        stock: 48,
        rating: 4.8,
        image: "https://picsum.photos/seed/product188/400/300"
    },
    {
        id: 189,
        name: "Anova Precision Cooker Nano",
        description: "Sous vide immersion circulator, 750 watts, Bluetooth connectivity, compact design",
        price: 99.00,
        category: "home",
        brand: "Anova",
        stock: 87,
        rating: 4.6,
        image: "https://picsum.photos/seed/product189/400/300"
    },
    {
        id: 190,
        name: "Cosori Electric Kettle",
        description: "1.7-liter capacity, borosilicate glass, auto shut-off, LED indicator, BPA-free",
        price: 39.99,
        category: "home",
        brand: "Cosori",
        stock: 167,
        rating: 4.6,
        image: "https://picsum.photos/seed/product190/400/300"
    },
    {
        id: 191,
        name: "Bodum French Press Coffee Maker",
        description: "34 oz capacity, borosilicate glass, stainless steel frame, 4-part filter",
        price: 29.95,
        category: "home",
        brand: "Bodum",
        stock: 198,
        rating: 4.5,
        image: "https://picsum.photos/seed/product191/400/300"
    },
    {
        id: 192,
        name: "Thermoworks Thermapen ONE",
        description: "Instant-read thermometer, 1-second readings, rotating display, waterproof",
        price: 105.00,
        category: "home",
        brand: "Thermoworks",
        stock: 143,
        rating: 4.9,
        image: "https://picsum.photos/seed/product192/400/300"
    },
    {
        id: 193,
        name: "Tovolo Silicone Spatula Set",
        description: "5-piece set, heat-resistant to 600°F, flexible silicone heads, ergonomic handles",
        price: 24.99,
        category: "home",
        brand: "Tovolo",
        stock: 234,
        rating: 4.6,
        image: "https://picsum.photos/seed/product193/400/300"
    },
    {
        id: 194,
        name: "Joseph Joseph Nest Measuring Cups",
        description: "8-piece nesting set, snap together for storage, includes ¼ to 1 cup measures",
        price: 19.99,
        category: "home",
        brand: "Joseph Joseph",
        stock: 187,
        rating: 4.7,
        image: "https://picsum.photos/seed/product194/400/300"
    },
    {
        id: 195,
        name: "Nordic Ware Baking Sheet Set",
        description: "3-piece aluminum sheet pans, natural finish, reinforced edges, made in USA",
        price: 39.99,
        category: "home",
        brand: "Nordic Ware",
        stock: 156,
        rating: 4.8,
        image: "https://picsum.photos/seed/product195/400/300"
    },
    {
        id: 196,
        name: "Microplane Premium Zester",
        description: "Stainless steel blade, ergonomic handle, protective cover, dishwasher safe",
        price: 14.95,
        category: "home",
        brand: "Microplane",
        stock: 289,
        rating: 4.8,
        image: "https://picsum.photos/seed/product196/400/300"
    },
    {
        id: 197,
        name: "Anchor Hocking Glass Mixing Bowls",
        description: "10-piece set, various sizes, tempered glass, microwave and dishwasher safe",
        price: 29.99,
        category: "home",
        brand: "Anchor Hocking",
        stock: 178,
        rating: 4.5,
        image: "https://picsum.photos/seed/product197/400/300"
    },
    {
        id: 198,
        name: "Rubbermaid Reveal Spray Mop",
        description: "Refillable bottle, non-marking wheels, washable microfiber pad, ergonomic grip",
        price: 29.99,
        category: "home",
        brand: "Rubbermaid",
        stock: 143,
        rating: 4.4,
        image: "https://picsum.photos/seed/product198/400/300"
    },
    {
        id: 199,
        name: "Swiffer WetJet Starter Kit",
        description: "Power mop, cleaning solution, extra pads, dual nozzle sprayer, absorbs dirt",
        price: 39.99,
        category: "home",
        brand: "Swiffer",
        stock: 198,
        rating: 4.3,
        image: "https://picsum.photos/seed/product199/400/300"
    },
    {
        id: 200,
        name: "Scotch-Brite Heavy Duty Scrub Sponges",
        description: "24-pack, cellulose sponge, scouring pad, removes tough messes, long-lasting",
        price: 19.99,
        category: "home",
        brand: "Scotch-Brite",
        stock: 412,
        rating: 4.6,
        image: "https://picsum.photos/seed/product200/400/300"
    }
];

module.exports = products;
